version: 2

updates:

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: monthly
      day: tuesday
      time: "11:00"
    open-pull-requests-limit: 10
    target-branch: devel

