name = "EQDSKReader"
uuid = "0d45e213-aaf5-468d-97e2-5d9984e6e107"
authors = ["Dmitri Portnov <d.portnov@iterrf.ru>"]
version = "1.0.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[compat]
julia = "~1.11"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Test"]
