name = "EQDSKReader"
uuid = "0d45e213-aaf5-468d-97e2-5d9984e6e107"
authors = ["Dmitri Portnov <d.portnov@iterrf.ru>"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
julia = "1.8.1"
